server:
  port: 80

spring:
    datasource:
      url: jdbc:mysql://192.168.159.128:3306/library
      username: root
      password: 1234
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

